id: PB2D6937B
initial_creation_type: ocr
source_metadata:
  volumes:
    f6135469d1884e4c8467e0d68b727346:
      base_file: v051.txt
      image_group_id: I1PD95896
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་སྟོང་ཕྲག་ཉི་ཤུ་ལྔ་པ།
      total_pages: 1818
      volume_number: 51
